### ISSUE TITLE
Speaker does not have sound when connected to Xmos audio out

### ISSUE THREAD

**Issue by KahHwa** [xmos/vocalfusion-avs-setup#26] opened 2018-07-18 03:32 UTC
When I used avsrun and ask a question, the speaker was initially able to play Alexa's voice. But now after I have installed a fresh raspbian stretch with Noobs and reinstalled the vocalfusion setup, alexa can still hear my commands and execute the command correctly but it I cant hear the sound from the speaker anymore.
Has there been a recent update ? Or is there some configuration that needs to be done on the raspberrypi after running the script.

**Comment by dfollent** [comment] 2018-07-18 08:12
Hi KahHwa,

Yes, vocalfusion-avs-setup was updated to v1.5 on 2018/07/18.  Can you please make sure you are using v1.5 (`cd vocalfusion-avs-setup ; git pull`) and then rerun the install script (`source ~/vocalfusion-avs-setup/auto_install.sh`)?

If you're still unable to hear audio over your speakers can you please send me the text output of the install script?

**Comment by dfollent** [comment] 2018-07-18 08:31
You can either copy the output directly from the terminal or run the following; 
`source ~/vocalfusion-avs-setup/auto_install.sh  2>&1 | tee output.txt`

**Comment by KahHwa** [comment] 2018-07-18 08:32
I have already done the installation. So, do I remove the directories and reinstall again ?

**Comment by dfollent** [comment] 2018-07-18 08:40
If you want to ensure a clean build you can do the following:
- Remove the directories `/home/pi/vocalfusion-avs-setup/` and `/home/pi/sdk-build`.
- Run the following commands in your terminal:
`cd ` 
`git clone https://github.com/xmos/vocalfusion-avs-setup`
`source ~/vocalfusion-avs-setup/auto_install.sh 2>&1 | tee output.txt`

This will ensure you are using the latest version of the VocalFusion AVS Dev Kit, and will copy the output of the installation to the file 'output.txt'.

**Comment by KahHwa** [comment] 2018-07-18 08:42
Here you go. 
[output.txt](https://github.com/xmos/vocalfusion-avs-setup/files/2205051/output.txt)

**Comment by dfollent** [comment] 2018-07-18 09:29
Hi KahHwa, 
Thank you for the text file. It doesn't look like there was any issue in the installation process.  Can you please investigate whether you can hear any audio from the Raspberry Pi via the VocalFusion device? Or is it just the AVS SDK that is muted? 

If you're unable to hear any audio at all, can you please send me your kernel version (`uname -a`) and  the contents of your asoundrc file (`cat ~/.asoundrc`)?

**Comment by KahHwa** [comment] 2018-07-18 09:32
I have checked the volume setting in the avs sdk. Both are not muted. I have also set alsamixer at maximum volume. 
Sorry I just left the office, I'll send you my kernel version and the contents of that file, when I as soon as I enter office tomorrow. Thanks for the help.

**Comment by dfollent** [comment] 2018-07-19 13:13
Hi KahHwa, 

I haven't been able to replicate your issue using the same kernel version.  Can you please check if any audio is coming through the VocalFusion device? For example, by playing a YouTube video in the Raspberry Pi's web browser.  

If you can't hear any audio at all, can you please make sure your devices are connected correctly as per the [Hardware Setup Guide](https://www.xmos.com/published/vocalfusion-4-mic-kit-for-amazon-avs-hardware-setup-guide). There may an issue with your I2S audio connection, or with the speakers themselves.

**Comment by larry-xmos** [comment] 2018-07-23 09:57
> I checked the signals and could see the I2S signals from the Raspberry Pi coming into the stereo DAC

Can you confirm this is the `I2S_DAC_DATA` net? Does the activity case when the far-end is silent (no speech or music)?

**Comment by mohamemu** [comment] 2018-07-24 01:40
Hi Larry,

Yes, I have confirmed this. I only see active signals when playing music or when Alexa responds.

**Comment by ThomasGmeinder** [comment] 2018-07-30 13:32
Can you please check the other I2S signals as well?
I2S_BCLK (XD36)
I2S_LRCLK (X1D37)

They are used for both I2S Master interfaces and can be accessed on the Extension Header J6.
See Hardware manual https://www.xmos.com/download/private/xCORE-VocalFusion-4-Mic-Kit-for-Amazon-AVS---Hardware-Manual%281.3%29.pdf
for more information.

And please confirm if this is true:
- The processed microphone signal gets to the RPi where the AVS client understands the keyword.
- But when Alexa responds (or you play other audio from the RPi) then the DAC is silent. 

Did you attach the scope to the DAC output as well to check if there is any difference in output signal when you expect an output vs when you expect silence.

**Comment by mohamemu** [comment] 2018-08-02 09:18
Hi Thomas,

Yes, I have checked the other I2S signals, all of them look good actually.
And yes, it is true that I can see in the RPi that the AVS client understands the keyword, and that the DAC is silent when Alexa responds or when I play a youtube video from the RPi.

Monitoring the DAC output on a scope, I do not see any active signal, no difference when I expect output or silence.

**Comment by ThomasGmeinder** [comment] 2018-09-20 07:17
Closing this issue as invalid. It was caused because the board was physically damaged by the user.

**Closed** 2018-09-24 15:50 UTC
