### ISSUE TITLE
snsr.h file missing for several of the installs

### ISSUE THREAD

**Issue by kieran-kohtz** [xmos/vocalfusion-avs-setup#54] opened 2022-05-04 14:09 UTC
I've looked online for the solution to this, and most of them seem to involve cloning https://github.com/Sensory/alexa-rpi and making sure that the right files are included.

**Comment by kieran-kohtz** [comment] 2022-05-04 14:10
Missing for 3100

```[ 88%] Building CXX object KWD/Sensory/src/CMakeFiles/SENSORY.dir/SensoryKeywordDetector.cpp.o
In file included from /home/pi/sdk-folder/avs-device-sdk/KWD/Sensory/src/SensoryKeywordDetector.cpp:20:
/home/pi/sdk-folder/avs-device-sdk/KWD/Sensory/include/Sensory/SensoryKeywordDetector.h:30:10: fatal error: snsr.h: No such file or directory
 #include "snsr.h"
          ^~~~~~~~
compilation terminated.
make[3]: *** [KWD/Sensory/src/CMakeFiles/SENSORY.dir/build.make:63: KWD/Sensory/src/CMakeFiles/SENSORY.dir/SensoryKeywordDetector.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:13048: KWD/Sensory/src/CMakeFiles/SENSORY.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:14820: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [Makefile:3737: SampleApp] Error 2```

**Comment by kieran-kohtz** [comment] 2022-05-04 14:56
missing for 3500

```[ 88%] Building CXX object KWD/Sensory/src/CMakeFiles/SENSORY.dir/SensoryKeywordDetector.cpp.o
In file included from /home/pi/sdk-folder/avs-device-sdk/KWD/Sensory/src/SensoryKeywordDetector.cpp:20:
/home/pi/sdk-folder/avs-device-sdk/KWD/Sensory/include/Sensory/SensoryKeywordDetector.h:30:10: fatal error: snsr.h: No such file or directory
 #include "snsr.h"
          ^~~~~~~~
compilation terminated.
make[3]: *** [KWD/Sensory/src/CMakeFiles/SENSORY.dir/build.make:63: KWD/Sensory/src/CMakeFiles/SENSORY.dir/SensoryKeywordDetector.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:13048: KWD/Sensory/src/CMakeFiles/SENSORY.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:14820: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [Makefile:3737: SampleApp] Error 2```

**Comment by kieran-kohtz** [comment] 2022-05-04 15:10
Missing for 3610-int

```[ 88%] Building CXX object KWD/Sensory/src/CMakeFiles/SENSORY.dir/SensoryKeywordDetector.cpp.o
In file included from /home/pi/sdk-folder/avs-device-sdk/KWD/Sensory/src/SensoryKeywordDetector.cpp:20:
/home/pi/sdk-folder/avs-device-sdk/KWD/Sensory/include/Sensory/SensoryKeywordDetector.h:30:10: fatal error: snsr.h: No such file or directory
 #include "snsr.h"
          ^~~~~~~~
compilation terminated.
make[3]: *** [KWD/Sensory/src/CMakeFiles/SENSORY.dir/build.make:63: KWD/Sensory/src/CMakeFiles/SENSORY.dir/SensoryKeywordDetector.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:13048: KWD/Sensory/src/CMakeFiles/SENSORY.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:14820: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [Makefile:3737: SampleApp] Error 2```

**Comment by lucianomartin** [comment] 2022-05-09 08:53
This problem is caused by this issue:
https://github.com/xmos/vocalfusion-avs-setup/issues/43

@mbanth do we have any solution about the missing Sensory repo? The simpler solution is to disable any KWD detection for all the products except xvf3615-ua/int, and to allow only the tap-to-talk mode, i.e. press 't' on the console.

**Comment by mbanth** [comment] 2022-05-09 09:49
@lucianomartin, I do not know of any particular solution that has been found for the missing public Sensory repositories.  It seems reasonable to me to disable Keyword detection in XVF3000, XVF3500, XVF3610-INT and XVF3610-UA at least.

I'm unsure about disabling Keyword detection for XVF3100 because I have been told that it includes that feature or something similar.  @lucianomartin, do you know anything about the keyword feature in XVF3100?

I'm also unsure about disabling Keyword detection for XVF3510-INT and XVF3510-UA because they can support the feature if used with the Red Embedded board.  @tomblackie-xmos, is XMOS going to support use of the AVS repositories with XVF3510 variants running on the Red Embedded board or not?  If not, we can disable Keyword detection for that product.

**Comment by lucianomartin** [comment] 2022-05-10 12:14
XVF3100 and XVF3000 have the same installation, so they both relied on the Sensory KWD. 
For a simple solution to allow the successful setup of all the products above, I disabled the steps to build the Sensory KWD engine. See https://github.com/xmos/avs-device-sdk/pull/75

**Comment by mbanth** [comment] 2022-05-10 12:49
Having spoken with @tomblackie-xmos, we have decided to leave keyword detection enabled in XVF3615-INT and XVF3615-UA and to disable it in XVF3610-INT, XVF3610-UA, XVF3510-INT, XVF3510-UA, XVF3500, XVF3100 and XVF3000.  Products with keyword detection disabled will operate with tap-to-talk.

**Comment by lucianomartin** [comment] 2022-05-19 14:09
Fixed in https://github.com/xmos/avs-device-sdk/releases/tag/v1.25.0.3

**Closed by lucianomartin** 2022-05-19 14:09 UTC
Labels: type:bug, size:S
